// app/src/main/java/com/example/workoutlogs/ui/workout/ExerciseNewScreen.kt
// Timestamp: 2025-05-14 21:25:00 CEST
// Scope: Composable screen for adding new exercises in WorkoutLogs app

package com.example.workoutlogs.ui.workout

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.navigation.NavController
import com.example.workoutlogs.data.model.Exercise

data class UiState(
    val name: String = "",
    val category: String = "",
    val notes: String? = null
)

@Composable
fun ExerciseNewScreen(
    navController: NavController,
    viewModel: ExerciseViewModel = hiltViewModel()
) {
    var uiState by remember { mutableStateOf(UiState()) }

    Scaffold { padding ->
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(padding)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            OutlinedTextField(
                value = uiState.name,
                onValueChange = { uiState = uiState.copy(name = it) },
                label = { Text("Exercise Name") },
                modifier = Modifier.fillMaxWidth()
            )
            OutlinedTextField(
                value = uiState.category,
                onValueChange = { uiState = uiState.copy(category = it) },
                label = { Text("Category") },
                modifier = Modifier.fillMaxWidth()
            )
            OutlinedTextField(
                value = uiState.notes ?: "",
                onValueChange = { uiState = uiState.copy(notes = it) },
                label = { Text("Notes") },
                modifier = Modifier.fillMaxWidth()
            )
            Button(
                onClick = {
                    viewModel.insertExercise(
                        Exercise(
                            id = 0, // Auto-generated by Room
                            name = uiState.name,
                            category = uiState.category,
                            notes = uiState.notes,
                            isSelected = false
                        )
                    )
                    navController.navigate("workout_exercises")
                },
                enabled = uiState.name.isNotBlank() && uiState.category.isNotBlank(),
                modifier = Modifier.fillMaxWidth()
            ) {
                Text("Save Exercise")
            }
        }
    }
}